export const cardInformation: Record<string, string> = {
  'Reading guide': `Reading guides are simple, low-tech tools that help students focus their eyes and attention on specific lines of text while reading. They can take the form of plastic rulers, tinted overlays, or highlighter strips placed directly on the page. These supports are handy for students who struggle with visual tracking, attention, or line skipping, such as those with dyslexia, ADHD, or visual processing difficulties.

By narrowing the visual field and emphasizing one line at a time, reading guides reduce cognitive load and visual clutter. Some guides include colored tints to minimize glare or contrast issues, while others use transparent windows or highlighted bands to isolate text. Easy to use across print materials or screens, they promote greater reading accuracy, fluency, and confidence – making text more accessible without adding technological complexity.`,

  'Spell checker': `A spell checker is a software tool that automatically detects and corrects misspelled words as a person types. It supports written communication by providing real-time feedback on spelling accuracy, helping users produce clearer and more professional text. Spell checkers are especially beneficial for students with dyslexia, learning disabilities, or challenges with written expression. By reducing errors and frustration, they allow writers to focus more on their ideas and content rather than on mechanical correctness.

Common features include automatic underlining of suspected errors, suggested corrections, and sometimes grammar or context-based checks. Spell checkers are built into most word processors, browsers, and digital devices, making them easy to access across classroom and home environments. They integrate seamlessly with typing software, note-taking apps, and communication platforms. The result is greater writing confidence, improved accuracy, and increased independence for learners who struggle with spelling or language mechanics.`,

  'Text-to-speech': `Text-to-speech (TTS) is a digital tool that converts written text into spoken words. It helps users who struggle with reading fluency, visual processing, or attention by allowing them to listen to written content instead of–or alongside–reading it. Students with dyslexia, visual impairments, or other reading challenges benefit most, as hearing text read aloud supports comprehension and focus. TTS tools reduce reading fatigue and make digital or printed materials more accessible across learning environments.

Text-to-speech tools typically offer adjustable voice options, playback speed controls, and synchronized highlighting to follow along visually. They can be used on computers, tablets, and mobile devices, often integrating with word processors, web browsers, and e-book readers. Some versions even allow offline use or language switching for multilingual learners. By transforming written text into audio, TTS promotes independent learning, increases reading comprehension, and gives users equitable access to academic and informational content.`,

  'Graphic organizers': `Graphic organizers are visual tools that help students organize ideas, plan writing, or understand relationships between concepts. They can be printed templates–like story maps, Venn diagrams, and flowcharts–or digital versions used on computers and tablets. These tools support learners who have difficulty with planning, sequencing, or seeing connections in text. By visually structuring information, they reduce cognitive load and make abstract ideas easier to grasp.

Graphic organizers come in many formats, such as concept maps, timelines, or cause-and-effect charts, and can be tailored to match learning tasks. Digital versions often include drag-and-drop features, color coding, and templates for different subjects, while paper versions allow for quick sketching and flexibility. Used in classrooms, study sessions, or collaborative settings, they help students plan writing, summarize reading, or analyze problems. Whether on paper or screen, graphic organizers strengthen comprehension, support memory, and improve written expression.`,

  'Portable word processor': `A portable word processor is a lightweight electronic device designed for typing, saving, and reviewing written work without the distractions or complexity of a full computer. It supports writing and note-taking for students who benefit from a simplified interface focused solely on text production. This tool is especially useful for individuals with attention challenges, fine motor difficulties, or limited computer access. Removing unnecessary features and focusing on function helps users concentrate on writing rather than managing technology.

Portable word processors typically feature full-size keyboards, small non-glare screens, and the ability to store or transfer documents digitally. They are often battery-powered, durable, and easy to use in classrooms or testing environments where laptops may be impractical. Files can usually be uploaded to computers or cloud systems for editing and printing. These devices promote independence and efficiency, allowing students to write comfortably and confidently in nearly any setting.`,

  'Audiobooks': `Audiobooks are recorded versions of printed or digital texts read aloud, allowing users to listen instead of reading visually. They support individuals who struggle with decoding, tracking, or sustaining attention during reading. Audiobooks are especially helpful for students with dyslexia, visual impairments, or learning disabilities that make traditional reading difficult. By presenting text in an auditory format, they remove barriers to comprehension and give learners equal access to literature and academic content.

Audiobooks are available in many formats, from CDs and digital downloads to streaming apps, and can be played on computers, tablets, or mobile devices. Many include adjustable playback speeds, bookmarking, and highlighting features for study use. They are commonly used in classrooms, libraries, and at home for independent learning or leisure reading. Listening to audiobooks enhances comprehension, vocabulary development, and engagement, while freeing students from the mechanical demands of decoding print.`,

  'Calculator': `A calculator is a handheld or digital device that performs mathematical operations, from basic arithmetic to complex equations. It supports students who struggle with computation, working memory, or number sequencing, allowing them to focus on problem-solving and concept understanding. Calculators are especially helpful for learners with dyscalculia, math-related learning difficulties, or fine motor challenges that make writing calculations difficult. By reducing the cognitive load of manual computation, calculators enable users to access higher-level math learning with greater independence.

Calculators come in many forms, including simple four-function models, scientific calculators, and digital or talking versions for individuals with visual impairments. They can be used in classrooms, testing environments, or at home to check work, complete assignments, or explore mathematical concepts. Some integrate with software or apps for accessibility or data recording. The use of calculators helps students engage more confidently in math, focusing on reasoning, strategy, and real-world application rather than calculation barriers.`,

  'Pencil grips': `Pencil grips are small attachments placed on pencils or pens to help students hold writing tools more comfortably and correctly. They support handwriting by promoting proper finger placement, reducing hand fatigue, and improving control. Pencil grips are especially beneficial for students with fine motor challenges, low muscle tone, or poor grasp patterns that make writing difficult. By making writing tools easier to handle, they increase endurance and legibility, helping students express ideas more easily.

Pencil grips come in various shapes, materials, and sizes–ranging from soft foam sleeves to molded silicone designs that guide finger placement. They are easy to use in classrooms, therapy sessions, or home settings and can fit most standard pencils and pens. Some grips provide sensory feedback or extra cushioning for comfort. These simple, low-cost supports help students write for longer periods, strengthen hand function, and build confidence in written communication.`,

  'Slant board': `A slant board is an angled writing surface that positions paper or reading material at a comfortable, upright angle. It supports posture, visual access, and fine motor control during writing or reading tasks. Slant boards are especially beneficial for students with low muscle tone, poor wrist positioning, visual tracking difficulties, or limited upper-body strength. By elevating the work surface, they promote proper alignment and reduce strain on the neck, shoulders, and wrists.

Slant boards may be adjustable or fixed at specific angles and can include clips or non-slip surfaces to hold materials in place. They are used in classrooms, therapy sessions, and home study areas to support handwriting, drawing, or reading activities. Some models fold flat for portability or can be used with tablets and books. This simple ergonomic tool improves comfort, hand control, and visual focus–helping students maintain endurance and precision in their work.`,

  'Voice recorder': `A voice recorder is a device or app that captures spoken words for later playback. It supports students who have difficulty taking written notes, organizing thoughts, or keeping pace during lectures or discussions. This tool is especially useful for learners with dyslexia, ADHD, or fine motor challenges that make writing slow or tiring. By allowing users to record and review information in their own words, it reduces reliance on handwriting and helps preserve key learning content.

Voice recorders range from simple handheld devices to digital or mobile app versions that store, organize, and share recordings. Many include features like timestamping, transcription, or voice labeling for easy review. They are commonly used in classrooms, study sessions, and meetings to capture ideas, lectures, or reminders. Voice recording promotes independence, improves comprehension and recall, and allows students to focus on listening and participation instead of note-taking speed.`,

  'Adapted keyboard': `An adapted keyboard is a modified input device designed to make typing easier and more accessible for individuals with physical, visual, or cognitive challenges. It supports written communication, computer use, and learning activities by adjusting key size, layout, or feedback. These keyboards are especially helpful for students with limited fine motor control, visual impairments, or difficulty using standard keyboards. By matching design to user needs, adapted keyboards reduce barriers to digital access and participation.

Adapted keyboards can include larger or smaller keys, high-contrast lettering, key guards, or custom layouts that simplify typing. Some are color-coded for easier visual scanning, while others connect wirelessly or integrate with assistive software for switch or touch access. They are used in classrooms, offices, and home environments to support writing, communication, and technology-based tasks. The result is improved accuracy, comfort, and independence in typing and computer interaction for users of all ages and abilities.`,

  'AAC communication': `Augmentative and Alternative Communication (AAC) tools provide ways for individuals to express themselves when speech is limited or not possible. These systems range from simple paper-based communication boards with symbols or written words to advanced dynamic display devices that generate speech output. AAC supports communication for users with conditions such as autism, cerebral palsy, Down syndrome, or speech and language impairments. By giving users a reliable voice or visual means to communicate, AAC removes barriers to participation, connection, and self-expression.

Paper-based systems use static grids or picture symbols that users can point to, while dynamic display systems use touchscreens and software that produce spoken words or sentences. Both types can be customized for vocabulary level, literacy skills, and daily routines. AAC tools are used in classrooms, therapy sessions, and home settings to support academic learning, social interaction, and independence. Providing access to language through AAC empowers users to share ideas, make choices, and engage fully in communication with others.`,

  'Visual timers': `Visual timers are tools that show the passage of time in a clear, visual format–often through color, shrinking shapes, or progress bars. They help individuals understand and manage time without relying solely on numbers or abstract concepts. Visual timers are especially helpful for students with ADHD, autism, or executive functioning challenges who benefit from seeing time as something tangible. By making time visible, these tools reduce anxiety, improve transitions, and support focus and task completion.

Visual timers can be mechanical devices with moving colored sections, digital timers on screens, or app-based versions with customizable displays and alerts. They are commonly used in classrooms, therapy sessions, and home routines to structure work periods, breaks, or transitions. Many versions include sound cues or adjustable visuals for different sensory needs. Visual timers build time awareness and self-regulation, helping users stay on task and feel more in control of their daily activities.`,

  'Peer buddy/partner support': `Peer buddy or partner support is a no-tech strategy that pairs students together to promote learning, participation, and social connection. The approach provides natural support within the classroom by matching a student who needs assistance with a trained or empathetic peer. It is especially helpful for learners with communication, social, or physical challenges who benefit from modeled behaviors and shared engagement. By using peer relationships as a bridge, this strategy reduces isolation and increases access to classroom activities and interaction.

Peer buddy systems can take many forms–academic partners, lab partners, reading buddies, or social companions during group work or transitions. Educators structure the roles to promote mutual benefit, ensuring both students practice collaboration, problem-solving, and empathy. The strategy works across all grade levels and settings, complementing other supports or assistive technologies. Peer partnerships foster inclusion, build confidence, and create authentic opportunities for communication and participation in everyday learning environments.`,

  'Single switch access': `Single switch access allows individuals to control computers, tablets, or communication devices using one simple input–a button, touchpad, or another single-press switch. It supports users with limited mobility, fine motor control, or coordination by providing an alternative way to navigate digital environments. This access method is especially beneficial for individuals with cerebral palsy, muscular dystrophy, spinal cord injuries, or other physical disabilities that limit traditional keyboard or touchscreen use. By replacing complex movements with a single, purposeful action, it enables users to engage more independently with technology.

Single switch systems work by scanning through options on a screen, allowing users to select items through timed or directed switch activations. They can connect to computers, tablets, or AAC devices through wired or wireless interfaces and are often adjustable for sensitivity, speed, and placement. Switches may be activated by a hand, head, foot, or other body part, depending on individual ability. This adaptive access method enhances communication, learning, and digital participation–providing a pathway to independence for users with significant motor challenges.`,

  'Preferential seating': `Preferential seating is a no-tech classroom strategy that involves placing a student in a location that best supports their learning and attention needs. The goal is to optimize access to instruction, minimize distractions, or accommodate sensory or physical needs. It is especially helpful for students with hearing or vision impairments, attention difficulties, or mobility challenges. By adjusting where a student sits rather than what tools they use, this strategy reduces barriers to focus, communication, and engagement.

Preferential seating may include sitting closer to the teacher or board, near positive role models, away from noise sources, or in easily accessible areas for mobility devices. The arrangement can be adapted throughout the day based on activity type or individual need. It is effective across grade levels and pairs well with other supports, such as assistive listening devices or visual aids. This simple environmental adjustment enhances participation, increases access to information, and supports a more equitable learning experience.`,

  'Chunk tasks': `Chunking tasks is a no-tech instructional strategy that involves breaking large or complex assignments into smaller, more manageable steps. This approach supports organization, attention, and task completion by reducing cognitive load and preventing overwhelm. It is especially beneficial for students with ADHD, executive functioning challenges, or learning disabilities who may struggle with sequencing or sustained focus. By simplifying information into clear segments, it helps learners stay engaged and experience consistent success throughout a task.

Teachers can use task chunking in written assignments, multi-step projects, or classroom directions by presenting one section at a time or using visual checklists. The strategy is effective across grade levels and content areas, often paired with timers, visual schedules, or peer supports. Chunking builds confidence and promotes self-regulation as students learn to approach work systematically. This simple adjustment increases independence, comprehension, and productivity–helping students see progress and maintain motivation from start to finish.`,

  'Magnification': `Magnification tools, such as handheld magnifying glasses, page lenses, or digital screen magnifiers, enlarge text and images to make visual information easier to see. They support reading, writing, and viewing details for individuals with low vision or visual fatigue. These tools are especially beneficial for students with visual impairments or age-related vision loss who need clearer access to printed or digital materials. By enlarging text and reducing visual strain, magnifiers make information more accessible and promote independent participation in learning and daily tasks.

Magnification can be achieved through simple handheld devices, stand magnifiers for books, or built-in digital zoom and screen magnification on computers and tablets. Many allow users to adjust magnification strength, contrast, or lighting for comfort and clarity. They are used across classroom, home, and workplace settings for reading assignments, viewing images, or completing close-up work. Simple magnification supports independence, improves reading accuracy, and helps users maintain visual access to both print and digital content.`,

  'Artificial intelligence': `Artificial intelligence (AI) can function as an assistive technology by providing personalized support for reading, writing, organization, and communication. AI tools use language processing, voice recognition, and adaptive learning to help users complete academic or daily tasks more efficiently. They are especially beneficial for students with learning disabilities, ADHD, or physical challenges that make traditional input or organization difficult. By adapting to individual needs and offering responsive feedback, AI reduces barriers to learning and empowers users to work more independently.

AI-based supports include text summarization, speech-to-text and text-to-speech conversion, grammar and style assistance, task planning, and conversational tutoring. These features can be accessed on computers, tablets, or mobile devices and are often built into common productivity tools. In classrooms or workplaces, AI helps users draft written work, organize ideas, and interact with digital content through natural language. Used responsibly, AI enhances accessibility, supports executive functioning, and expands opportunities for self-directed learning and communication.`
};
